name: coin-workflow

# trigger
on:
  push:
    branches:
      - "release/v[0-9]+.[0-9]+"

jobs:
  # name of your job
  Build-Coin-Sign-And-Notify:
    runs-on: fedora-latest
    steps:
      - name: Checkout
        id: Checkout-step
        uses: actions/checkout@v3
        with:
          ref: ${{github.ref}}
          path: ${{github.workspace}}/${{github.ref_name}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUBUSERNAME }}
          password: ${{ secrets.DOCKERHUBACCESSTOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        id: build-and-push
        with:
          file: ${{github.workspace}}/${{github.ref_name}}/Dockerfile
          push: true
          tags: ${{secrets.DOCKERHUBUSERNAME}}/coin-app:${{github.sha}}
      # - name: Install Cosign
      #   uses: sigstore/cosign-installer@v3.5.0
      # - name: Sign image with a key
      #   run: |
      #     cosign sign --key env://COSIGN_PRIVATE_KEY ${TAG}
      #   env:
      #     TAG: ${{secrets.DOCKERHUBUSERNAME}}/go-fortune@${{ steps.build-and-push.outputs.digest }}
      #     COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
      #     COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
      #     DIGEST: ${{ steps.build-and-push.outputs.digest }}
      
